### ISSUE TITLE
Error on async select

### ISSUE THREAD

**Issue by danieldaeschle** [ImangazalievM/ReActiveAndroid#8]
I'm using Kotlin. I got this error:

```
02-14 13:36:57.260 23657-23692/<> W/System.err: io.reactivex.exceptions.OnErrorNotImplementedException: Database info referenced with table <>.shared.models.ReportEntry not found.
02-14 13:36:57.260 23657-23692/<> W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
02-14 13:36:57.261 23657-23692/<> W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
02-14 13:36:57.261 23657-23692/<> W/System.err:     at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
02-14 13:36:57.261 23657-23692/<> W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onError(SingleSubscribeOn.java:73)
02-14 13:36:57.261 23657-23692/<> W/System.err:     at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:48)
02-14 13:36:57.261 23657-23692/<> W/System.err:     at io.reactivex.Single.subscribe(Single.java:3096)
02-14 13:36:57.261 23657-23692/<> W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
02-14 13:36:57.261 23657-23692/<> W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:463)
02-14 13:36:57.261 23657-23692/<> W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
02-14 13:36:57.261 23657-23692/<> W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
02-14 13:36:57.261 23657-23692/<> W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-14 13:36:57.262 23657-23692/<> W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
02-14 13:36:57.262 23657-23692/<> W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
02-14 13:36:57.262 23657-23692/<> W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
02-14 13:36:57.262 23657-23692/<> W/System.err:     at java.lang.Thread.run(Thread.java:764)
02-14 13:36:57.262 23657-23692/<> W/System.err: Caused by: java.lang.IllegalArgumentException: Database info referenced with table <>.shared.models.ReportEntry not found.
02-14 13:36:57.262 23657-23692/<> W/System.err:     at com.reactiveandroid.ReActiveAndroid.getDatabaseForTable(ReActiveAndroid.java:120)
02-14 13:36:57.262 23657-23692/<> W/System.err:     at com.reactiveandroid.ReActiveAndroid.getTableName(ReActiveAndroid.java:186)
02-14 13:36:57.262 23657-23692/<> W/System.err:     at com.reactiveandroid.query.Select$From.getPartSql(Select.java:181)
02-14 13:36:57.262 23657-23692/<> W/System.err:     at com.reactiveandroid.query.QueryBase.getSql(QueryBase.java:19)
02-14 13:36:57.262 23657-23692/<> W/System.err:     at com.reactiveandroid.query.ResultQueryBase.fetch(ResultQueryBase.java:26)
02-14 13:36:57.262 23657-23692/<> W/System.err:     at com.reactiveandroid.query.ResultQueryBase$1.call(ResultQueryBase.java:57)
02-14 13:36:57.262 23657-23692/<> W/System.err:     at com.reactiveandroid.query.ResultQueryBase$1.call(ResultQueryBase.java:54)
02-14 13:36:57.263 23657-23692/<> W/System.err:     at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
02-14 13:36:57.263 23657-23692/<> W/System.err: 	... 10 more
02-14 13:36:57.264 23657-23691/<> W/System.err: io.reactivex.exceptions.OnErrorNotImplementedException: Database info referenced with table <>.shared.models.ReportEntry not found.
02-14 13:36:57.264 23657-23691/<> W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
02-14 13:36:57.264 23657-23691/<> W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
02-14 13:36:57.264 23657-23691/<> W/System.err:     at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
02-14 13:36:57.264 23657-23691/<> W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onError(SingleSubscribeOn.java:73)
02-14 13:36:57.264 23657-23691/<> W/System.err:     at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:48)
02-14 13:36:57.265 23657-23691/<> W/System.err:     at io.reactivex.Single.subscribe(Single.java:3096)
02-14 13:36:57.265 23657-23691/<> W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
02-14 13:36:57.265 23657-23691/<> W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:463)
02-14 13:36:57.265 23657-23691/<> W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
02-14 13:36:57.265 23657-23691/<> W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
02-14 13:36:57.265 23657-23691/<> W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-14 13:36:57.266 23657-23691/<> W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
02-14 13:36:57.266 23657-23691/<> W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
02-14 13:36:57.266 23657-23691/<> W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
02-14 13:36:57.266 23657-23691/<> W/System.err:     at java.lang.Thread.run(Thread.java:764)
02-14 13:36:57.266 23657-23691/<> W/System.err: Caused by: java.lang.IllegalArgumentException: Database info referenced with table <>.shared.models.ReportEntry not found.
02-14 13:36:57.266 23657-23691/<> W/System.err:     at com.reactiveandroid.ReActiveAndroid.getDatabaseForTable(ReActiveAndroid.java:120)
02-14 13:36:57.266 23657-23691/<> W/System.err:     at com.reactiveandroid.ReActiveAndroid.getTableName(ReActiveAndroid.java:186)
02-14 13:36:57.266 23657-23691/<> W/System.err:     at com.reactiveandroid.query.Select$From.getPartSql(Select.java:181)
02-14 13:36:57.266 23657-23691/<> W/System.err:     at com.reactiveandroid.query.QueryBase.getSql(QueryBase.java:19)
02-14 13:36:57.266 23657-23691/<> W/System.err:     at com.reactiveandroid.query.ResultQueryBase.fetch(ResultQueryBase.java:26)
02-14 13:36:57.266 23657-23691/<> W/System.err:     at com.reactiveandroid.query.ResultQueryBase$1.call(ResultQueryBase.java:57)
02-14 13:36:57.267 23657-23691/<> W/System.err:     at com.reactiveandroid.query.ResultQueryBase$1.call(ResultQueryBase.java:54)
02-14 13:36:57.267 23657-23691/<> W/System.err:     at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
02-14 13:36:57.267 23657-23691/<> W/System.err: 	... 10 more
02-14 13:36:57.267 23657-23691/<> I/Process: Sending signal. PID: 23657 SIG: 9
```

I have the following code:

```Kotlin
Select
                .from(ReportEntry::class.java)
                .fetchAsync()
                .subscribeOn(Schedulers.io())
                .subscribe { reportEntries ->
                    entries.addAll(reportEntries.filter { it.date.monthOfYear == month }
                            .sortedBy { it.date })
                }
```

**Comment by danieldaeschle** [comment]
Oh man, i got it. Forgot this line:

`.addModelClasses(ReportEntry::class.java)`
